// backend/src/services/issueService.js
const gitlab = require('./gitlabService');

async function createIssueFromAnalysis(projectId, { pipelineId, job, analysis }) {
  const title = `[AUTO] CI failed: ${job.name} in pipeline ${pipelineId}`;
  let description = `**AI Analysis**\n\n**Stage:** ${analysis.stage || job.name}\n\n**Root cause:**\n${analysis.root_cause}\n\n**Suggested fix:**\n${analysis.suggested_fix}\n\n**Confidence:** ${analysis.confidence || 0}\n\n**Log excerpt:**\n\`\`\`\n${job.shortLog || 'attached in comment'}\n\`\`\`\n\n_This issue was auto-generated by the AI DevOps Assistant._`;

  // create issue in GitLab
  const issue = await gitlab.createIssue(projectId, title, description, ['ai:analysis', 'auto-created']);
  return issue;
}

module.exports = { createIssueFromAnalysis };
